name: Build Android App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up keystore
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > keystore/release.keystore
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "storeFile=../keystore/release.keystore" >> keystore.properties
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ptz-camera-controller
          path: app/build/outputs/apk/release/app-release.apk

      - name: Generate QR Code
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sudo apt-get install -y qrencode
          qrencode -o qrcode.png "https://github.com/${{ github.repository }}/releases/latest/download/ptz-camera-controller.apk"
          
      - name: Upload QR Code
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: qrcode
          path: qrcode.png

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/release/app-release.apk
            qrcode.png
          name: PTZ Camera Controller ${{ github.ref_name }}
          body: |
            # PTZ Camera Controller ${{ github.ref_name }}
            
            ## Installation
            
            ### Option 1: Scan QR Code
            Scan the QR code image attached to this release with your Android tablet.
            
            ### Option 2: Direct Download
            Download the APK file directly from this release page.
            
            ## Changes in this version
            - New features and improvements
            - Bug fixes
            
            ## Requirements
            - Android 6.0 (Marshmallow) or higher
            - Bluetooth and/or WiFi capability
          draft: false
          prerelease: false